name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail" # 数据库的名称
database_id = "${D1_DATABASE_ID}" # 使用占位符引用环境变量

[[kv_namespaces]]
binding = "kv"
id = "${KV_NAMESPACE_ID}" # 使用占位符引用环境变量

[[r2_buckets]]
binding = "r2"
bucket_name = "${R2_BUCKET_NAME}" # 使用占位符引用环境变量

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


#[vars]
#orm_log = false
#domain = []				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
#admin = ""				#管理员的邮箱	示例: admin@example.com
#jwt_secret = ""			#jwt令牌的密钥,随便填一串字符串